# To run: conda env create -f environment.yml
name: nerf
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - cudatoolkit==11.2.2
    - tensorflow-gpu==2.13.1
    - numpy==1.26.4
    - matplotlib==3.8.4
    - imageio==2.34.1
    - imageio-ffmpeg==0.4.9
    - configargparse==1.7
    - imagemagick==7.1.1_31
